### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by novaprimexex**
tin counter code from max

### CODE REVIEW

**Comment by novaprimexex** [comment]
this code counts the number of tins passing in front of the ultrasonic sensor. if a tin without a label passes, the device should turn on the red led

**Comment by tardate** [comment]
@novaprimexex thanks for this! are you still working on it or do you want me to review/merge already?

couple of things: 
* add a README.md - it would be good to explain how the label detection works. I had a brief look but was not clear what is connected to A0 - i gather that is the key!
* add a schematic? (I often use fritzing or EasyEDA for simple circuits like this)

btw, before I merge, one thing I should ensure you are OK with: once merged, this will fall under my MIT open source license (see LICENSE in the root of the repo). Agreed?

**Comment by novaprimexex** [comment]
Sure I'll do just that. Add a fritzing schematic and a readme explanation.
Thanks for the feedback

**Comment by novaprimexex** [comment]
[New Compressed Folder update.zip](https://github.com/tardate/LittleArduinoProjects/files/1857875/New.Compressed.Folder.update.zip)

**Comment by tardate** [comment]
@novaprimexex I moved the sources around a bit and cleaned up. See https://github.com/tardate/LittleArduinoProjects/tree/master/playground/tin_counter - look OK?

Note: I added fritzing source file and schematic. does this look right? Two points I wanted to clarify:
* source seemed to have a buzzer on pin 9, so I added it in the schematic. it's not in the pic, so not sure if you meant to leave it there?
* Not 100% sure about the A0 contacts. is it going to be pulled high to VCC if the tin makes contact, and broken circuit if label in the way? if so, seems like a pulldown resistor on A0 would be a good idea to add (to ensure 0 if no contact, i.e. don't leave it floating)
* there's an uninitialised `withoutLabel` pin in the source: `int withoutLabel; ... pinMode(withoutLabel, OUTPUT);` this appears to be obsolete and should be removed?

Please feel free to send another pull request with any more changes..

**Comment by novaprimexex** [comment]
ok thank you for the merge, would surely still look into the project and do
just as you advised.

**Pull request merged**
